language: node_js
node_js:
  - '6.10.1'

notifications:
  email:
    recipients:
      weymouth@umich.edu

# blocklist - branches not used for testing: any branch starting with 'spike'
branches:
  except:
  - /^spike-.*$/

sudo: required

addons:
  hosts:
  - mctest.localhost

env:
  global:
    - MC_SERVICE_PORT=5002
    - MC_API_SERVICE_PORT=5004
    - MC_PUB_SERVICE_PORT=5026
    - MCDB_PORT=30815
    - MCDB_CONNECTION="localhost:$MCDB_PORT"
    - MCDIR=~/file_data
    - MCDB_DIR=~/testdb
    - RETHINKDB_HTTP_PORT=8090
    - RETHINKDB_CLUSTER_PORT=31815
    - MC_ES_URL="http://localhost:9500"
    - MC_LOG_DIR=/tmp
    - MCDB_TYPE=rethinkdb
    - MCDB_NAME=materialscommons
    - MCDB_FILE=test_data/test_rethinkdb_dump.tar.gz
    - RETHINKDB_CLUSTER_PORT=31815
    - RETHINKDB_HTTP_PORT=8090
    - MC_DOI_SERVICE_URL=https://ezid.lib.purdue.edu/
    - MC_DOI_PUBLISHER='Materials Commons'
    - MC_DOI_PUBLICATION_BASE=http://mcpub.localhost/#/details
    - MC_DOI_NAMESPACE='doi:10.5072/FK2'

before_install:
  - export MC_APP_DIR=`pwd`
    # RethinkDB
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    # Yarn
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update

install:
  - sudo apt-get install nginx
  - sudo apt-get install rethinkdb
  - sudo apt-get install yarn

  - node --version

  # Note: using yarn because it is more robust to network problems then npm install
  - yarn install

  - sudo pip install rethinkdb
  - sudo pip install Flask
  - sudo pip install pytest
  - sudo pip install pbkdf2

  - npm install -g node-gyp@3.5.0
  - npm install -g gulp-cli
  - npm install -g gulp

  - pushd ~
  - mkdir .materialscommons
  - sudo mkdir -p /etc/nginx/conf.d

  - git clone --depth=50 --branch=sprint https://github.com/materials-commons/mcapi.git
  - cd mcapi/python
  - export MC_PYTHON_API_DIR=`pwd`
  - sudo pip install -r requirements.txt
  - sudo python setup.py install

  # Note: github does not store or recover empty directories
  #       this is needed for testing - creating empty dir
  - mkdir -p test/test_data/test_upload_data/test_upload_dir/sub_directory_c/empty_dir
  - cd test/test_data/test_config_data
  - cp travisconfig.json ~/.materialscommons/config.json
  - sudo cp mctest.localhost.conf /etc/nginx/conf.d/
  - popd
  - pwd

before_script:
  # - sudo nginx
  # it appears that nginx is already running (started at install time?)
  - sudo nginx -s relaod
  - rethinkdb --driver-port $MCDB_PORT --cluster-port $RETHINKDB_CLUSTER_PORT --http-port $RETHINKDB_HTTP_PORT --daemon
  - sleep 5
  - ls $MCDB_FILE
  - rethinkdb restore $MCDB_FILE --connect $MCDB_CONNECTION --force
  - cd $MC_APP_DIR
  - pushd backend/scripts/templates/
  - ./run.sh
  - popd
  - pushd backend
  - gulp build-mcapi-server
  - sleep 5
  - node sbin/mcapi/mcapi.js -p $MCAPI_SERVER_PORT > ${MC_LOG_DIR}/mcapi.out.${SERVERTYPE} 2>&1&
  - sleep 5
  - popd

script:
  - npm run-script test-no-html
