language: node_js
node_js:
  - '0.10.33'

env:
  global:
    - MCDIR=/tmp/mcdir
    - MCDB_CONNECTION=localhost:30815
    - MCDB_TYPE=rethinkdb
    - MCDB_NAME=materialscommons
    - MCDB_FILE=$HOME/test-data/rethinkdb_dump_test_data.tar.gz

install:
  - 'nvm install v5.3.0'
  - 'npm install -g bower'
  - 'npm install -g gulp-cli'
  - 'npm install'

script:
  - 'cd backend'
  - 'mocha "**/specs/*-spec.js"'
