language: node_js
node_js:
  - '0.10.33'

notifications:
  email:
    recipients:
      weymouth@umich.ed

python:
  - '2.7'

# blocklist - branches not used for testing: any branch starting with 'spike'
branches:
  except:
  - /^spike-.*$/

sudo: required

env:
  global:
    - MC_SERVICE_PORT=5002
    - MC_API_SERVICE_PORT=5004
    - MC_PUB_SERVICE_PORT=5026
    - MCDB_PORT=30815
    - MCDB_CONNECTION="localhost:$MCDB_PORT"
    - MCDB_DIR=~/testdb
    - RETHINKDB_HTTP_PORT=8090
    - RETHINKDB_CLUSTER_PORT=31815
    - MC_ES_URL="http://localhost:9500"
    - MC_LOG_DIR=/tmp
    - MCDB_TYPE=rethinkdb
    - MCDB_NAME=materialscommons
    - MCDB_FILE=test_data/test_ready_rethinkdb_dump_2017-02-01.tar.gz
    - RETHINKDB_CLUSTER_PORT=31815
    - RETHINKDB_HTTP_PORT=8090

before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb
  - 'nvm install v5.3.0'
  - sudo pip install rethinkdb
  - sudo pip install Flask
  - sudo pip install pytest
  - node --version
  - pip list

before_script:
  - npm list --depth=0
  - which mocha
  - rethinkdb --driver-port $MCDB_PORT --cluster-port $RETHINKDB_CLUSTER_PORT --http-port $RETHINKDB_HTTP_PORT --daemon
  - sleep 5
  - rethinkdb restore $MCDB_FILE --connect $MCDB_CONNECTION --force

script:
  - npm run-script test-no-html
  - pytest --ignore=node_modules/
